package net.uoneweb.mapbox.uploader.mapbox

import com.fasterxml.jackson.annotation.JsonProperty
import java.net.URI

data class Tileset(
    val type: String,
    val center: Array<Double>,
    val created: String,
    val description: String,
    @JsonProperty("filesize") val fileSize: Int,
    val id: String,
    val modified: String,
    val name: String,
    val visibility: String,
    val status: String
) {

    fun getTilesetId(): String {
        val paths = URI(id).path.split("/")
        return paths?.get(2) ?: ""
    }

    // Override equals and hashcode because this class has Array member.
    // Code below is Generated by IDE.

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Tileset

        if (type != other.type) return false
        if (!center.contentEquals(other.center)) return false
        if (created != other.created) return false
        if (description != other.description) return false
        if (fileSize != other.fileSize) return false
        if (id != other.id) return false
        if (modified != other.modified) return false
        if (name != other.name) return false
        if (visibility != other.visibility) return false
        if (status != other.status) return false

        return true
    }

    override fun hashCode(): Int {
        var result = type.hashCode()
        result = 31 * result + center.contentHashCode()
        result = 31 * result + created.hashCode()
        result = 31 * result + description.hashCode()
        result = 31 * result + fileSize
        result = 31 * result + id.hashCode()
        result = 31 * result + modified.hashCode()
        result = 31 * result + name.hashCode()
        result = 31 * result + visibility.hashCode()
        result = 31 * result + status.hashCode()
        return result
    }

}
